name: Publish package to GitHub Packages
on: push
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Check if it's the right tag
        id: is_correct_tag
        run: echo ::set-output name=is_correct_tag::$(if [ "${GITHUB_REF##refs/tags/}" = "1.0.0" ]; then echo true; else echo false; fi)
      - name: Publish package
        if: steps.is_correct_tag.outputs.is_correct_tag == 'true'
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.sdk }}